/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package view.gui;

import view.utils.ZooData;
import exceptions.*;
import java.awt.Color;

/**
 *
 * @author iker-hurtado-caballo
 */
public class JFrameGerente extends javax.swing.JFrame {

    /**
     * Creates new form JFrameGerente
     */
    public JFrameGerente() {
        initComponents();
        setup();
    }

    public void setup() {
        int ingresos = ZooData.zoo.calcularIngresos();
        jLabelIngresos.setVisible(false);
        jLabelIngresos.setText("Los ingresos actuales del zoo son de " + ingresos + "€.");

        if (ingresos >= 0) {
            jLabelIngresos.setForeground(Color.GREEN);
        } else {
            jLabelIngresos.setForeground(Color.RED);
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jButtonAnadirAnimal = new javax.swing.JButton();
        jButtonVerIngresos = new javax.swing.JButton();
        jButtonContratarEmpleado = new javax.swing.JButton();
        jButtonAnadirHabitat = new javax.swing.JButton();
        jButtonDespedirEmpleado = new javax.swing.JButton();
        jButtonQuitarAnimal = new javax.swing.JButton();
        jButtonVerEmpleados = new javax.swing.JButton();
        jButtonExpulsarVisitante = new javax.swing.JButton();
        jButtonVerVisitantes = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jButtonGoBack = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        jLabelIngresos = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setBackground(new java.awt.Color(255, 255, 255));

        jButtonAnadirAnimal.setBackground(new java.awt.Color(153, 204, 255));
        jButtonAnadirAnimal.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jButtonAnadirAnimal.setForeground(new java.awt.Color(255, 255, 255));
        jButtonAnadirAnimal.setText("Añadir animal al Zoo");
        jButtonAnadirAnimal.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonAnadirAnimalActionPerformed(evt);
            }
        });

        jButtonVerIngresos.setBackground(new java.awt.Color(153, 204, 255));
        jButtonVerIngresos.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jButtonVerIngresos.setForeground(new java.awt.Color(255, 255, 255));
        jButtonVerIngresos.setText("Ver Ingresos del Zoo");
        jButtonVerIngresos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonVerIngresosActionPerformed(evt);
            }
        });

        jButtonContratarEmpleado.setBackground(new java.awt.Color(153, 204, 255));
        jButtonContratarEmpleado.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jButtonContratarEmpleado.setForeground(new java.awt.Color(255, 255, 255));
        jButtonContratarEmpleado.setText("Contratrar empleado");
        jButtonContratarEmpleado.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonContratarEmpleadoActionPerformed(evt);
            }
        });

        jButtonAnadirHabitat.setBackground(new java.awt.Color(153, 204, 255));
        jButtonAnadirHabitat.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jButtonAnadirHabitat.setForeground(new java.awt.Color(255, 255, 255));
        jButtonAnadirHabitat.setText("Añadir hábitat al zoo");
        jButtonAnadirHabitat.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonAnadirHabitatActionPerformed(evt);
            }
        });

        jButtonDespedirEmpleado.setBackground(new java.awt.Color(153, 204, 255));
        jButtonDespedirEmpleado.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jButtonDespedirEmpleado.setForeground(new java.awt.Color(255, 255, 255));
        jButtonDespedirEmpleado.setText("Despedir empleado");
        jButtonDespedirEmpleado.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonDespedirEmpleadoActionPerformed(evt);
            }
        });

        jButtonQuitarAnimal.setBackground(new java.awt.Color(153, 204, 255));
        jButtonQuitarAnimal.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jButtonQuitarAnimal.setForeground(new java.awt.Color(255, 255, 255));
        jButtonQuitarAnimal.setText("Quitar animal del zoo");
        jButtonQuitarAnimal.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonQuitarAnimalActionPerformed(evt);
            }
        });

        jButtonVerEmpleados.setBackground(new java.awt.Color(153, 204, 255));
        jButtonVerEmpleados.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jButtonVerEmpleados.setForeground(new java.awt.Color(255, 255, 255));
        jButtonVerEmpleados.setText("Ver empleados del zoo");
        jButtonVerEmpleados.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonVerEmpleadosActionPerformed(evt);
            }
        });

        jButtonExpulsarVisitante.setBackground(new java.awt.Color(153, 204, 255));
        jButtonExpulsarVisitante.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jButtonExpulsarVisitante.setForeground(new java.awt.Color(255, 255, 255));
        jButtonExpulsarVisitante.setText("Expulsar visitante del zoo");
        jButtonExpulsarVisitante.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonExpulsarVisitanteActionPerformed(evt);
            }
        });

        jButtonVerVisitantes.setBackground(new java.awt.Color(153, 204, 255));
        jButtonVerVisitantes.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jButtonVerVisitantes.setForeground(new java.awt.Color(255, 255, 255));
        jButtonVerVisitantes.setText("Ver todos los visitantes");
        jButtonVerVisitantes.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonVerVisitantesActionPerformed(evt);
            }
        });

        jLabel1.setFont(new java.awt.Font("Britannic Bold", 1, 24)); // NOI18N
        jLabel1.setText("Bienvenido, gerente!");

        jButtonGoBack.setBackground(new java.awt.Color(51, 102, 255));
        jButtonGoBack.setFont(new java.awt.Font("Liberation Sans", 1, 15)); // NOI18N
        jButtonGoBack.setForeground(new java.awt.Color(255, 255, 255));
        jButtonGoBack.setText("Volver al menú");
        jButtonGoBack.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonGoBackActionPerformed(evt);
            }
        });

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/oficina.jpg"))); // NOI18N

        jLabelIngresos.setFont(new java.awt.Font("Liberation Sans", 0, 24)); // NOI18N
        jLabelIngresos.setForeground(new java.awt.Color(102, 255, 102));
        jLabelIngresos.setText("Los ingresos actuales del Zoo son XXXX€");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(138, 138, 138)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addComponent(jButtonAnadirAnimal, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jButtonVerIngresos, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jButtonContratarEmpleado, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jButtonAnadirHabitat, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jButtonDespedirEmpleado, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jButtonQuitarAnimal, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jButtonVerEmpleados, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jButtonVerVisitantes, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jButtonGoBack, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jButtonExpulsarVisitante))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 142, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(jLabel2)
                        .addGap(153, 153, 153))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(jLabelIngresos)
                        .addGap(22, 22, 22))))
            .addGroup(layout.createSequentialGroup()
                .addGap(123, 123, 123)
                .addComponent(jLabel1)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jLabelIngresos))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(35, 35, 35)
                                .addComponent(jLabel1)
                                .addGap(18, 18, 18)
                                .addComponent(jButtonAnadirAnimal)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jButtonVerIngresos)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jButtonContratarEmpleado)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jButtonAnadirHabitat)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jButtonDespedirEmpleado)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(jButtonQuitarAnimal)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(jButtonVerEmpleados)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(jButtonExpulsarVisitante)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(jButtonVerVisitantes))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(66, 66, 66)
                                .addComponent(jLabel2)))
                        .addGap(18, 18, 18)
                        .addComponent(jButtonGoBack)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 25, Short.MAX_VALUE)))
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButtonAnadirAnimalActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonAnadirAnimalActionPerformed
        JFrameAnadirAnimal jFrameAnadirAnimal = new JFrameAnadirAnimal();
        jFrameAnadirAnimal.setVisible(true);
        this.dispose();

    }//GEN-LAST:event_jButtonAnadirAnimalActionPerformed

    private void jButtonVerIngresosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonVerIngresosActionPerformed
        jLabelIngresos.setVisible(true);
    }//GEN-LAST:event_jButtonVerIngresosActionPerformed

    private void jButtonContratarEmpleadoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonContratarEmpleadoActionPerformed
        JFrameContratarEmpleado jFrameContratarEmpleado = new JFrameContratarEmpleado();
        jFrameContratarEmpleado.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_jButtonContratarEmpleadoActionPerformed

    private void jButtonAnadirHabitatActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonAnadirHabitatActionPerformed
        JFrameAnadirHabitat jFrameAnadirHabitat = new JFrameAnadirHabitat();
        jFrameAnadirHabitat.setVisible(true);
        this.dispose();    }//GEN-LAST:event_jButtonAnadirHabitatActionPerformed

    private void jButtonDespedirEmpleadoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonDespedirEmpleadoActionPerformed
        JFrameDespedirEmpleado jFrameDespedirEmpleado = new JFrameDespedirEmpleado();
        jFrameDespedirEmpleado.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_jButtonDespedirEmpleadoActionPerformed

    private void jButtonQuitarAnimalActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonQuitarAnimalActionPerformed
        JFrameQuitarAnimal jFrameQuitarAnimal = new JFrameQuitarAnimal();
        jFrameQuitarAnimal.setVisible(true);
        this.dispose();     }//GEN-LAST:event_jButtonQuitarAnimalActionPerformed

    private void jButtonVerEmpleadosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonVerEmpleadosActionPerformed
        JFrameVerEmpleados jFrameVerEmpleados = new JFrameVerEmpleados();
        jFrameVerEmpleados.setVisible(true);
        this.dispose();     }//GEN-LAST:event_jButtonVerEmpleadosActionPerformed

    private void jButtonExpulsarVisitanteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonExpulsarVisitanteActionPerformed
        JFrameExpulsarVisitante jFrameExpulsarVisitante = new JFrameExpulsarVisitante();
        jFrameExpulsarVisitante.setVisible(true);
        this.dispose();       }//GEN-LAST:event_jButtonExpulsarVisitanteActionPerformed

    private void jButtonVerVisitantesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonVerVisitantesActionPerformed
        JFrameVerVisitantes jFrameVerVisitantes = new JFrameVerVisitantes();
        jFrameVerVisitantes.setVisible(true);
        this.dispose(); 
    }//GEN-LAST:event_jButtonVerVisitantesActionPerformed

    private void jButtonGoBackActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonGoBackActionPerformed
        this.dispose();
        JFrameHome jFrameHome = new JFrameHome();
        jFrameHome.setVisible(true);
    }//GEN-LAST:event_jButtonGoBackActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(JFrameGerente.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(JFrameGerente.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(JFrameGerente.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(JFrameGerente.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new JFrameGerente().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButtonAnadirAnimal;
    private javax.swing.JButton jButtonAnadirHabitat;
    private javax.swing.JButton jButtonContratarEmpleado;
    private javax.swing.JButton jButtonDespedirEmpleado;
    private javax.swing.JButton jButtonExpulsarVisitante;
    private javax.swing.JButton jButtonGoBack;
    private javax.swing.JButton jButtonQuitarAnimal;
    private javax.swing.JButton jButtonVerEmpleados;
    private javax.swing.JButton jButtonVerIngresos;
    private javax.swing.JButton jButtonVerVisitantes;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabelIngresos;
    // End of variables declaration//GEN-END:variables
}
