/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package view.gui;

import view.utils.ZooData;
import exceptions.*;
import java.text.ParseException;
import java.text.SimpleDateFormat;
import java.util.Date;
import model.*;

/**
 *
 * @author iker-hurtado-caballo
 */
public class JFrameContratarEmpleado extends javax.swing.JFrame {

    /**
     * Creates new form JFrameAnadirAnimal
     */
    public JFrameContratarEmpleado() {
        initComponents();
        setup();
    }

    public void setup() {
        jLabelInvalidSalary.setVisible(false);
        jLabelInvalidName.setVisible(false);
        jLabelInvalidBirthDate.setVisible(false);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        jTextAreaEmployeeName = new javax.swing.JTextArea();
        jScrollPane3 = new javax.swing.JScrollPane();
        jTextAreaBirthDate = new javax.swing.JTextArea();
        jButtonCheckAnimalForm = new javax.swing.JButton();
        jLabel4 = new javax.swing.JLabel();
        jScrollPane4 = new javax.swing.JScrollPane();
        jTextAreaSalary = new javax.swing.JTextArea();
        jLabelInvalidSalary = new javax.swing.JLabel();
        jLabelInvalidBirthDate = new javax.swing.JLabel();
        jLabelInvalidName = new javax.swing.JLabel();
        jButtonVolver = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setFont(new java.awt.Font("Liberation Sans", 1, 36)); // NOI18N
        jLabel1.setText("Contratar empleado");

        jLabel2.setText("Nombre del empleado");

        jLabel3.setText("Fecha de nacimiento");

        jTextAreaEmployeeName.setColumns(20);
        jTextAreaEmployeeName.setRows(5);
        jScrollPane2.setViewportView(jTextAreaEmployeeName);

        jTextAreaBirthDate.setColumns(20);
        jTextAreaBirthDate.setRows(5);
        jScrollPane3.setViewportView(jTextAreaBirthDate);

        jButtonCheckAnimalForm.setText("Contratar empleado");
        jButtonCheckAnimalForm.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonCheckAnimalFormActionPerformed(evt);
            }
        });

        jLabel4.setText("Sueldo");

        jTextAreaSalary.setColumns(20);
        jTextAreaSalary.setRows(5);
        jScrollPane4.setViewportView(jTextAreaSalary);

        jLabelInvalidSalary.setForeground(new java.awt.Color(255, 51, 0));
        jLabelInvalidSalary.setText("Introduce un salario válido");

        jLabelInvalidBirthDate.setForeground(new java.awt.Color(255, 51, 0));
        jLabelInvalidBirthDate.setText("Introduce una fecha de nacimiento válida");

        jLabelInvalidName.setForeground(new java.awt.Color(255, 51, 0));
        jLabelInvalidName.setText("El empleado ya existe");

        jButtonVolver.setText("Volver");
        jButtonVolver.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonVolverActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap(69, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(jButtonVolver, javax.swing.GroupLayout.PREFERRED_SIZE, 184, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jButtonCheckAnimalForm, javax.swing.GroupLayout.PREFERRED_SIZE, 184, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap())
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabelInvalidSalary)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addComponent(jLabel3)
                                .addComponent(jLabel2)
                                .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(jScrollPane2)
                                .addComponent(jScrollPane3)
                                .addComponent(jLabel4)
                                .addComponent(jScrollPane4))
                            .addComponent(jLabelInvalidBirthDate)
                            .addComponent(jLabelInvalidName))
                        .addGap(78, 78, 78))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(22, 22, 22)
                .addComponent(jLabel1)
                .addGap(18, 18, 18)
                .addComponent(jLabel2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(2, 2, 2)
                .addComponent(jLabelInvalidName)
                .addGap(18, 18, 18)
                .addComponent(jLabel3)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabelInvalidBirthDate)
                .addGap(18, 18, 18)
                .addComponent(jLabel4)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane4, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabelInvalidSalary)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 226, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButtonCheckAnimalForm, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButtonVolver, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButtonCheckAnimalFormActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonCheckAnimalFormActionPerformed
        String employeeName = jTextAreaEmployeeName.getText();
        boolean error = false;
        int employeeSalary = 0;
        setup();

        for (Empleado empleado : ZooData.zoo.getEmpleados()) {
            if (empleado.getNombre().equalsIgnoreCase(employeeName)) {
                jLabelInvalidName.setVisible(true);
                error = true;
                break;
            }
        }

        try {
            employeeSalary = Integer.parseInt(jTextAreaSalary.getText());
        } catch (NumberFormatException ex) {
            jLabelInvalidSalary.setVisible(true);
            error = true;
        }
        String employeeBirthDate = jTextAreaBirthDate.getText();

        SimpleDateFormat dateFormat = new SimpleDateFormat("dd/MM/yyyy");
        Date birthDate = null;
        try {
            birthDate = dateFormat.parse(employeeBirthDate);
        } catch (ParseException e) {
            jLabelInvalidBirthDate.setVisible(true);
            error = true;
        }

        if (error) {
            return;
        }

        Cuidador empleado = new Cuidador();
        empleado.setNombre(employeeName);
        empleado.setFecha(birthDate);
        empleado.setSueldo(employeeSalary);
        ZooData.zoo.getEmpleados().add(empleado);
        this.dispose();

        JFrameGerente jFrameGerente = new JFrameGerente();
        jFrameGerente.setVisible(true);

    }//GEN-LAST:event_jButtonCheckAnimalFormActionPerformed

    private void jButtonVolverActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonVolverActionPerformed
        JFrameGerente jFrameGerente = new JFrameGerente();
        jFrameGerente.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_jButtonVolverActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(JFrameContratarEmpleado.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(JFrameContratarEmpleado.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(JFrameContratarEmpleado.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(JFrameContratarEmpleado.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new JFrameContratarEmpleado().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButtonCheckAnimalForm;
    private javax.swing.JButton jButtonVolver;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabelInvalidBirthDate;
    private javax.swing.JLabel jLabelInvalidName;
    private javax.swing.JLabel jLabelInvalidSalary;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JScrollPane jScrollPane4;
    private javax.swing.JTextArea jTextAreaBirthDate;
    private javax.swing.JTextArea jTextAreaEmployeeName;
    private javax.swing.JTextArea jTextAreaSalary;
    // End of variables declaration//GEN-END:variables
}
