/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package view.gui;

import view.utils.ZooData;
import exceptions.*;

/**
 *
 * @author iker-hurtado-caballo
 */
public class JFrameEmpleadoDashboard extends javax.swing.JFrame {

    /**
     * Creates new form JFrameGerente
     */
    public JFrameEmpleadoDashboard() {
        initComponents();
        setup();
    }

    public void setup() {
        jLabelWelcome.setText("Bienvenido, " + ZooData.zoo.getCurrentEmpleado().getNombre());
        jLabelGanancias.setText("Ganancias totales: " + ZooData.zoo.getCurrentEmpleado().getSueldo() + "€");
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jButtonRealizarCuidados = new javax.swing.JButton();
        jLabelWelcome = new javax.swing.JLabel();
        jButtonGoBack = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        jButtonCobrarSueldo = new javax.swing.JButton();
        jLabelGanancias = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jButtonRealizarCuidados.setText("Realizar cuidados a animal");
        jButtonRealizarCuidados.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonRealizarCuidadosActionPerformed(evt);
            }
        });

        jLabelWelcome.setFont(new java.awt.Font("Liberation Sans", 1, 24)); // NOI18N
        jLabelWelcome.setText("Bienvenido, empleado!");

        jButtonGoBack.setBackground(new java.awt.Color(255, 102, 102));
        jButtonGoBack.setFont(new java.awt.Font("Liberation Sans", 1, 15)); // NOI18N
        jButtonGoBack.setText("Finalizar Jornada");
        jButtonGoBack.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonGoBackActionPerformed(evt);
            }
        });

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/cuidador.jpg"))); // NOI18N

        jButtonCobrarSueldo.setText("Cobrar sueldo");
        jButtonCobrarSueldo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonCobrarSueldoActionPerformed(evt);
            }
        });

        jLabelGanancias.setFont(new java.awt.Font("Liberation Sans", 1, 24)); // NOI18N
        jLabelGanancias.setForeground(new java.awt.Color(0, 204, 51));
        jLabelGanancias.setText("Ganancias totales: ");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addContainerGap()
                                .addComponent(jLabelWelcome)
                                .addGap(94, 94, 94))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(133, 133, 133)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(jButtonRealizarCuidados, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(jButtonGoBack, javax.swing.GroupLayout.PREFERRED_SIZE, 206, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jButtonCobrarSueldo, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                .addGap(122, 122, 122)))
                        .addComponent(jLabel2))
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jLabelGanancias)))
                .addContainerGap(176, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(25, 25, 25)
                .addComponent(jLabelWelcome)
                .addGap(100, 100, 100)
                .addComponent(jButtonRealizarCuidados)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jButtonCobrarSueldo)
                .addGap(20, 20, 20)
                .addComponent(jButtonGoBack)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabelGanancias)
                .addContainerGap())
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(37, Short.MAX_VALUE)
                .addComponent(jLabel2)
                .addGap(31, 31, 31))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButtonRealizarCuidadosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonRealizarCuidadosActionPerformed
        this.dispose();
        JFrameRealizarCuidados jFrameRealizarCuidados = new JFrameRealizarCuidados();
        jFrameRealizarCuidados.setVisible(true);
    }//GEN-LAST:event_jButtonRealizarCuidadosActionPerformed

    private void jButtonGoBackActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonGoBackActionPerformed
        this.dispose();
        JFrameHome jFrameHome = new JFrameHome();
        jFrameHome.setVisible(true);
    }//GEN-LAST:event_jButtonGoBackActionPerformed

    private void jButtonCobrarSueldoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonCobrarSueldoActionPerformed
        ZooData.zoo.getCurrentEmpleado().setSueldo(ZooData.zoo.getCurrentEmpleado().getSueldo() * 2);
        setup();
    }//GEN-LAST:event_jButtonCobrarSueldoActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(JFrameEmpleadoDashboard.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(JFrameEmpleadoDashboard.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(JFrameEmpleadoDashboard.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(JFrameEmpleadoDashboard.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new JFrameEmpleadoDashboard().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButtonCobrarSueldo;
    private javax.swing.JButton jButtonGoBack;
    private javax.swing.JButton jButtonRealizarCuidados;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabelGanancias;
    private javax.swing.JLabel jLabelWelcome;
    // End of variables declaration//GEN-END:variables
}
